# Setup
name:           Nick Carroll
title:          Nick Carroll
tagline:        'Software Professional'
description:    'I work for <a href="https://covata.com" target="_blank">Covata</a>, but the opinions expressed here are my own, and no other party necessarily agrees with them.'
url:            http://nickcarroll.me

# Dependencies
markdown:       redcarpet
pygments:       true

# Permalinks
permalink:      pretty

# Pagination
paginate:       5

# About
author:
    name:           'Nick Carroll'
    url:            http://nickcarroll.me
